AWS_ACCESS_KEY:  'AKIAIABRS3BFQ4TBB5NA'
AWS_SECRET_KEY:  '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'
AWS_BUCKET:      'ianjonesfirehose'
AWS_REGION:      'us-east-1'
SECRET_KEY:      'sk_test_8fxn5cs5rZUu5aiOLZLDnbMF'
PUBLISHABLE_KEY: 'pk_test_FNqntB9Ib0TnLmvYaMGqxEzs'